PageBundle\Entity\StaticPage:
    type:  entity
    table: cms_page
    repositoryClass: PageBundle\Entity\PageRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        slug:
            type: string
            length: 255
        content:
            type: text
        enabled:
            type: boolean
        path:
            type: string
            length: 255